version: "3.8"
services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - .:/app
      - /app/node_modules