name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production  # Optional but recommended for tracking
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Only needed if you're using Railway CLI
      - name: Setup Railway CLI
        run: |
          npm install -g @railway/cli
          railway login --token ${{ secrets.RAILWAY_TOKEN }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}  # Proper secret access

      # Run your test suite (recommended)
      - name: Run tests
        run: |
          npm install
          npm test

      # Deployment notification
      - name: Notify deployment
        run: echo "Triggering Railway auto-deploy"