name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Optional: Install and configure Railway CLI
      - name: Setup Railway CLI
        run: |
          npm install -g @railway/cli
          railway login --token ${{ secrets.RAILWAY_TOKEN }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      # Optional: Run tests before deployment
      - name: Run tests
        run: |
          npm install
          npm test

      # Trigger Railway deployment (automatic if connected via GitHub)
      - name: Notify Railway
        run: |
          echo "Code pushed to main branch - Railway auto-deploy will handle the rest"
          # Alternative manual trigger:
          # railway up --detach