name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install --production=false
        
      # Run tests ONLY if test script exists
      - name: Run tests (if any)
        run: |
          if grep -q '"test":' package.json; then
            npm test
          else
            echo "No test script found, skipping tests"
          fi
        continue-on-error: true  # Continue even if tests fail
        
      # Install Railway CLI and authenticate
      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      # Deploy to Railway with correct commands
      - name: Trigger Deployment
        run: |
          echo "Attempting deployment with Railway CLI..."
          railway link --environment production
          railway up --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}