name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Railway CLI
        run: |
          npm install -g @railway/cli
          echo "${{ secrets.RAILWAY_TOKEN }}" | railway login
          
      - name: Trigger Deployment
        run: |
          railway up --service chat-app --detach